import type { WorkoutTemplate } from "./types";
import { normalizeWorkoutSteps } from "./normalize";

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: "easy-run",
    label: "Easy Run",
    sportCode: "running",
    workoutType: "easy",
    title: "Easy Run",
    steps: [
      {
        type: "warmup",
        duration: 5,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        type: "run",
        duration: 40,
        distance: null,
        targetType: "heart_rate",
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: "Easy effort",
      },
      {
        type: "cooldown",
        duration: 5,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "long-run",
    label: "Long Run",
    sportCode: "running",
    workoutType: "long_run",
    title: "Long Run",
    steps: [
      {
        type: "warmup",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        type: "run",
        duration: 90,
        distance: null,
        targetType: "heart_rate",
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: "Steady aerobic pace",
      },
      {
        type: "cooldown",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "recovery-run",
    label: "Recovery Run",
    sportCode: "running",
    workoutType: "recovery",
    title: "Recovery Run",
    steps: [
      {
        type: "run",
        duration: 30,
        distance: null,
        targetType: "heart_rate",
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: "Very easy",
      },
    ],
  },
  {
    id: "threshold",
    label: "Threshold Workout",
    sportCode: "running",
    workoutType: "threshold",
    title: "Threshold Intervals",
    steps: [
      {
        type: "warmup",
        duration: 15,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        repeatCount: 4,
        steps: [
          {
            type: "interval",
            duration: 8,
            distance: null,
            targetType: "pace",
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "Threshold pace",
          },
          {
            type: "recovery",
            duration: 3,
            distance: null,
            targetType: null,
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "Jog",
          },
        ],
      },
      {
        type: "cooldown",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "vo2-running",
    label: "VO2 Max Workout",
    sportCode: "running",
    workoutType: "intervals",
    title: "VO2 Max Intervals",
    steps: [
      {
        type: "warmup",
        duration: 15,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        repeatCount: 5,
        steps: [
          {
            type: "interval",
            duration: 3,
            distance: null,
            targetType: "pace",
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "Hard",
          },
          {
            type: "recovery",
            duration: 3,
            distance: null,
            targetType: null,
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "Walk/jog",
          },
        ],
      },
      {
        type: "cooldown",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "hill-repeats",
    label: "Hill Repeats",
    sportCode: "running",
    workoutType: "hills",
    title: "Hill Repeats",
    steps: [
      {
        type: "warmup",
        duration: 15,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        repeatCount: 6,
        steps: [
          {
            type: "interval",
            duration: 2,
            distance: null,
            targetType: null,
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "Hard uphill",
          },
          {
            type: "recovery",
            duration: 2,
            distance: null,
            targetType: null,
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "Jog down",
          },
        ],
      },
      {
        type: "cooldown",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "endurance-ride",
    label: "Endurance Ride",
    sportCode: "cycling",
    workoutType: "long_run",
    title: "Endurance Ride",
    steps: [
      {
        type: "warmup",
        duration: 15,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        type: "ride",
        duration: 120,
        distance: null,
        targetType: "heart_rate",
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: "Steady endurance",
      },
      {
        type: "cooldown",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "sweet-spot",
    label: "Sweet Spot",
    sportCode: "cycling",
    workoutType: "threshold",
    title: "Sweet Spot Ride",
    steps: [
      {
        type: "warmup",
        duration: 15,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        type: "ride",
        duration: 60,
        distance: null,
        targetType: "power",
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: "88–93% FTP",
      },
      {
        type: "cooldown",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "threshold-ride",
    label: "Threshold Ride",
    sportCode: "cycling",
    workoutType: "threshold",
    title: "Threshold Ride",
    steps: [
      {
        type: "warmup",
        duration: 20,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        repeatCount: 3,
        steps: [
          {
            type: "interval",
            duration: 12,
            distance: null,
            targetType: "power",
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "FTP effort",
          },
          {
            type: "recovery_ride",
            duration: 5,
            distance: null,
            targetType: null,
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: null,
          },
        ],
      },
      {
        type: "cooldown",
        duration: 10,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
  {
    id: "vo2-cycling",
    label: "VO2 Max Ride",
    sportCode: "cycling",
    workoutType: "intervals",
    title: "VO2 Max Ride",
    steps: [
      {
        type: "warmup",
        duration: 20,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
      {
        repeatCount: 5,
        steps: [
          {
            type: "interval",
            duration: 4,
            distance: null,
            targetType: "power",
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: "VO2 max",
          },
          {
            type: "recovery_ride",
            duration: 4,
            distance: null,
            targetType: null,
            targetMin: null,
            targetMax: null,
            targetZoneId: null,
            targetZoneName: null,
            notes: null,
          },
        ],
      },
      {
        type: "cooldown",
        duration: 15,
        distance: null,
        targetType: null,
        targetMin: null,
        targetMax: null,
        targetZoneId: null,
        targetZoneName: null,
        notes: null,
      },
    ],
  },
];

export function templatesForSport(sportCode: string | null | undefined) {
  if (!sportCode) return [];
  return WORKOUT_TEMPLATES.filter((t) => t.sportCode === sportCode).map((t) => ({
    ...t,
    steps: normalizeWorkoutSteps(t.steps),
  }));
}
